### PR TITLE
Add full range of PAGE-ICE scenarios

### PR DESCRIPTION
**Pull request by jrising**
This implements explicit permafrost and albedo feedbacks (which had just been locked to their NDCs scenario values). The tests only check the NDCs and 2 degC Target with surface albedo feedback scenarios, but those are now all working. I imagine that most of the other scenarios will work too.

@fhdezram @P-Wlich I suggest that you do not try merging in these changes. They're coming too late for you projects, which is a shame.
@jkikstra You might want to try to merge this in. Most of the changes should merge in smoothly.

### CODE REVIEW

**Comment by jkikstra** [comment]
Thanks James! I have merged it into my branch. As everything seems to be working just fine, I will most likely use this then as the basis of my model.

**Comment by jkikstra** [comment]
@jrising please note that the permafrost changes in the `mcs.jl` should probably be in lower case, as that is how it is referred to in the model code. Running MC will throw an error if it isn't.

**Comment by jkikstra** [comment]
image
I'm not sure if this is just me, or whether the (GDP)** data for 1.5C and 2.0C are not yet usable.

** I have not checked for population

**Comment by jrising** [comment]
@jkikstra Thanks for flagging these. I always forget to test the MC.
I've made a PR changing the parameters to lower case, and I had missed the JULES permafrost MC parameters, so I added those: PR #42 .

On the 2.0C and 1.5C scenarios, can you send me how you're testing them? Here's what I just did, and the GDP doesn't end up with the very low values you see:
```
julia> m = getpage("2 degC Target")
julia> run(m)
julia> m[:GDP, :gdp]
10×8 Array{Union{Missing, Float64},2}:
 1.87314e7  1.91433e7  1.04904e7  …  1.62082e7  8.93755e6  9.3159e6 
 2.18674e7  2.35653e7  1.27003e7     2.98024e7  1.43243e7  1.3423e7 
 2.58317e7  2.79471e7  1.50027e7     5.09068e7  2.36683e7  1.90445e7
 3.03351e7  3.26582e7  1.748e7       7.85287e7  3.89961e7  2.59946e7
 4.41231e7  4.77366e7  2.43216e7     1.58154e8  1.20036e8  4.71458e7
 6.20014e7  6.84152e7  3.16573e7  …  2.25549e8  2.64458e8  6.87437e7
 1.18559e8  1.37889e8  5.06986e7     3.73657e8  9.93044e8  1.25254e8
 2.02277e8  2.58884e8  6.84118e7     4.2488e8   1.89969e9  1.59152e8
 3.14132e8  4.56011e8  8.27718e7     4.3896e8   2.60808e9  1.75086e8
 4.51434e8  7.5846e8   9.34292e7     4.42604e8  3.04408e9  1.81863e8
```

I also checked the `RCP8.5 & SSP5` to see if that's what was acting oddly in your graphs, but it's fine too.

**Comment by jkikstra** [comment]
@jrising thank you for checking! Indeed the previous was actually just a wrong plot on my side; everything behaves as expected.

image

**Pull request merged**
