### PR TITLE
Implement James' converging growth rates

### PR DESCRIPTION
**Pull request by pwaidelich**
GDP growth rates were obtained by merely adding up pcGDP and population growth rates found in the dropbox: https://www.dropbox.com/home/NextGen%20IAMs/PAGE/sspextend

Per capita consumption for the current master:
grafik
For the converging growth rates:
grafik

### CODE REVIEW

**Comment by jrising** [comment]
I'd like to keep the whole process together. For going from my CSVs to the updated files, do you have a script that can go in the repository? I think we should put everything needed to generate the input data into a `prepdata` folder.

**Comment by pwaidelich** [comment]
I've sent you an invite as collaborator for the small repo with the script. It uses the csv outputs of your dropbox code as inputs but the header still has to be modified to fit Mimi format requirements, I did that manually.

**Comment by jrising** [comment]
Thanks for sending these. I've added in the materials into a new `preproc` directory on the master branch.

I'm not sure how this will affect the unit tests, and we need to maintain a set of unit tests that pass (the current set fails because of a fix to non-Burke damages, see issue #38, but otherwise works). How many things does this break?

I think we may have to allow this to be "turned off", and the current unit tests run with this off.

**Comment by jkikstra** [comment]
This was implemented [here](https://github.com/openmodels/mimi-page-2020.jl/commit/1ecf3bde884a0f0a50167ebbe7fd161ae307da5b) for [updating PAGE-ICE to PAGE-2020](https://github.com/openmodels/mimi-page-2020.jl/pull/48).

**Comment by jkikstra** [comment]
close as was implemented in PAGE-2020 updating effort https://github.com/openmodels/mimi-page-2020.jl/pull/34#issuecomment-588202280

**Pull request closed without merging**
