### PR TITLE
Support package use of MimiPAGE2020

### PR DESCRIPTION
**Pull request by jrising**
This builds off of https://github.com/openmodels/MimiPAGE2020.jl/pull/65, but is intended to allow the model to be run either as a package (typically for those who are just using PAGE) or as a stand-alone repository (for those developing it).

e.g., using this as a package:
```
julia> import MimiPAGE2020
[ Info: Precompiling MimiPAGE2020 [daa1807e-96ac-4669-bc57-6ed081383131]

julia> m = MimiPAGE2020.get_model()
Mimi.Model
  Module: Mimi
  Components:
    ComponentId(MimiPAGE2020.RCPSSPScenario)
    ComponentId(MimiPAGE2020.ClimateTemperature)
    ComponentId(MimiPAGE2020.PermafrostSiBCASA)
...

julia> run(m)
```

Using this for model development:
```
julia> include("src/main_model.jl")
getpage (generic function with 5 methods)

julia> m = getpage()
Mimi.Model
  Module: Mimi
  Components:
    ComponentId(Main.RCPSSPScenario)
    ComponentId(Main.ClimateTemperature)
    ComponentId(Main.PermafrostSiBCASA)
...

julia> run(m)
```

### CODE REVIEW

**Comment by jrising** [comment]
@davidanthoff What I've done here is copy over your changes, but implementing the further thoughts that I mentioned in my reply to you. To wit:
 - I left out your changes to the individual unit tests. This lets them be run either as a package or not.
 - I moved the function definitions from `climate_model.jl` and `main_model.jl` to a `src/models` directory, so that I could restore the previous interface. If you're using the package, `MimiPAGE2020.jl` imports the function definitions. But you can also include `climate_model.jl` or `main_model.jl` on their own and get all of the necessary includes that go with those functions.

That second point is going to be important when we bring the "extended models" into the main repo (currently in `analysis/allscc`), which are different ways to build the models with different includes, some of which define components named identically to the main model.

**Comment by lrennels** [comment]
@jrising per a recent comment on the forum (https://forum.mimiframework.org/t/mimipage2020-joining-the-registry/169) I think it would be great to have MimiPAGE2020 usable as a package, even if it's not officially registered in the General Registry.  Anything I can do to help push this part over the line?  We could also add a few sentences to the README instructing on how to add the package ie. 

```
Julia> ]
pkg> add https://github.com/openmodels/MimiPAGE2020.jl
```

**Comment by jrising** [comment]
@lrennels Thanks! I agree, it would be great. I was hoping for some kind of sanity check on this before merging it. I think there are considerable benefits to setting up the code to be able to either run as a package or as a stand-alone. I'm fairly certain that this preserves the "stand-alone" functionality, but I'm less confident that it ticks all the boxes for a package. So, I have two questions to finish this up:

1. Is there a way to load a directory as a package, so that I can make a unit test for the package functionality?

2. Are you aware of any stumbling blocks that I'm missing for setting the model up this way? Basically, all I've done is allowed the same code to either be run by various scripts or through functions in `MimiPAGE2020.jl`. I do heavily rely on relative paths to ensure that I never have to refer to a `MimiPAGE2020` package in unit tests.

**Comment by jrising** [comment]
@lrennels Okay, I think I found a way to do it-- by activating and then instantiating the `Project.toml` in the local directory. It's not how you would use the code if you wanted to use it as a package (you would just add it like a normal package), but it's good for testing the functionality.

Once the test completes, I'll be good to merge this branch in and add this to the model registry.

**Comment by lrennels** [comment]
Sorry @jrising I missed this, and understand that you want to keep your testing working properly and not sacrifice that for package functionality, it's your package after all! 

That's a good question about unit testing for package functionality, and I have to admit I don't have a good answer ... maybe @davidanthoff  does?  What you did in `test_package.jl` seems reasonable at least locally, I'm not sure how Continuous Integration testing will handle it.

**Comment by lrennels** [comment]
I'm can also clone the repo and work on the failing test for you since this is per my request :)

**Comment by lrennels** [comment]
The other option is to directly `include MimiPAGE2020.jl` and then import the module and run tests, such as

```
julia> activate .
julia> instantiate
julia> include "src/MimiPAGE2020.jl"
julia> using .MimiPAGE2020 # imports Main.MimiPAGE2020 to namespace
```
although in that case you'd still need to directly import non-exported functions at the top of your test files which is what we often do with Mimi.

**Comment by lrennels** [comment]
Per a unit test that the package mode works I haven't actually added one so not sure how that'll work on continuous integration, but what you did looks good for local testing at least.

**Comment by jrising** [comment]
I got a silly error from the unit test:
```
LoadError: ArgumentError: Package Pkg not found in current path:
  - Run `import Pkg; Pkg.add("Pkg")` to install the Pkg package.
```
I just need to add the Pkg package so that I can add the Pkg package.

I'm hoping this is something odd about using `using Pkg` with Pkg. I've tried replacing it with `import Pkg`.

**Comment by jrising** [comment]
@lrennels Okay, I finally figured out that I did not need to separately install the package in my unit test (though I still don't understand why any `import Pkg` lines would fail). Since I've merged in your github actions from PAGE09, which were designed for package testing, I was already in a position to import `MimiPAGE2020`.

I'm merging this in. What's the process for getting this into the model registry?

**Comment by lrennels** [comment]
@jrising 

Great thank you!  For now you can just tag a new version of the package and then we should be able to add it to an environment with:
```
pkg> add https://github.com/openmodels/MimiPAGE2020.jl
```
and then if you want to register the package with the General Registry I can ping @davidanthoff to remind us how to do that it’s pretty easy at this point and I can certainly do it as wel.   We are moving away from our personal Mimi Registry but you could register with the General Registry so that it’s possible to do 
```
pkg> add MimiPAGE2020
```

**Comment by jrising** [comment]
Great. The package is waiting an apparently mandatory 3 days to be added to the General Registry, but I've tagged a new release.

**Pull request merged**
