### PR TITLE
Annual and growth refactoring

### PR DESCRIPTION
**Pull request by jrising**
@jkikstra @pwaidelich This is currently a draft PR, but I wanted to alert you both because it is a significant refactoring of your code.

The vision is that we want to eliminate as much of the code duplication in the `components/extensions` directory as possible. We have two ways to do this:

1. Adding configuration options: I've done this in the emissions components (e.g., `compute_gdpfeedback` in `CH4emissions.jl`), since this is potentially generally useful. Also, in the damage functions, the difference between the `..._annual.jl` and `_annualGrowth.jl` components was whether we interpolate the parameters, so I turned that into a configuration option rather than two different files.

2. Splitting and daisy-chaining components. In many cases, the annual computations made sense as separate components. The way that these could then be used are to add both the non-annual and annual versions of a component to a model, and use the outputs of the non-annual component as inputs to the annual component. In some cases, I went a step further and split annual-calculations and growth-calculations into separate components, where you could add the non-growth-non-annual component and then either or both of those to get back the annual-growth results.

In the case of `EquityWeighting`, I have not (yet) found a way to disentangle the annual, growth, and annual-growth logic, so I've left it as-is.

I also have not yet changed the code that uses these components to actually use the configuration parameters or daisy-chainings. That's one of the reasons this is a draft.

Here's what's left to do:
 - [x] Get the standard model unit tests running again.
 - [x] Create a set of unit tests for the annual and growth results from the paper.
 - [x] Update the code in `analysis/allscc` to use the refactoring and get it running.
 - [x] Get the new unit tests running.

### CODE REVIEW

**Comment by jrising** [comment]
@lrennels Here's where I'm refactoring the extensions code.

One of my solutions is to add configuration options, which then use extra parameters and code. Take a look at the changes to `src/components/CH4emissions.jl`. The problem is that leaves un-set parameters in components when the configurations aren't used, which causes `set_leftover_params!` (and the unit tests) to fail.

Is there a better way to do this? I could make the configuration parameters into global variables, if it would allow me to conditionally not have the parameters in the component at all. (Can you use `if` in the parameter definition section?)

**Comment by lrennels** [comment]
Hi @jrising thanks for pointing me to this I will put some thought to it.  Within the `@defcomp` macro at this point I don't think we can use control logic like `if ... then` unfortunately. At first glance I like the idea of configuration options, and I actually ran into a similar problem using configuration options and unset parameters ... I will try to recall what I did in that scenario :). My guess is I put those computations into a separate component that I could decide to add, or not, depending on the configuration. 

Just so I"m clear, in the `CH4emissions.jl` example, the `Parameter` that would be unset would be these right:
```
  # read in counterfactual GDP in absence of growth effects (gdp_leveleffects) and actual GDP
   gdp = Parameter(index=[time, region], unit="\$M")
   gdp_leveleffect   = Parameter(index=[time, region], unit="\$M")
   emfeed_emissionfeedback = Parameter(unit="none", default=1.)
```

**Comment by jkikstra** [comment]
Hi @jrising - great to see that you're picking this up and moving it forward, making the extensions cleaner and more manageable - which was always going to be required to make it more useful for future work. 
Unfortunately I don't have the capacity at the moment to stay close to this, so please go ahead with it without me at this stage. If you have anything specific though, I'm of course happy to have a look.

**Comment by jrising** [comment]
@lrennels Exactly. Is there a way to give `gdp` and `gdp_leveleffect` a default value (e.g., all 0's)? That would solve the problem.

**Comment by jrising** [comment]
@jkikstra Thanks for the note. I'll let you know if I have any specific questions.

**Comment by pwaidelich** [comment]
Hi @jrising - this looks like a great step to streamline the code and make it more usable for future work! I'm currently booked out with other research projects, but I could contribute from March onward if that is OK with your timeline. And of course I'm always available for questions

**Comment by lrennels** [comment]
@jrising great question, in theory yes you should be able to set defaults that are multidimensional.  My concern would be that it wouldn't be very flexible ie. you'd have to decide ahead of time the size like `default = fill(0., 10, 16)` or something where you might prefer flexibility if someones sets a new `time` dimension. I suppose we could similarly be setting it to all zeros with `update_param!` in the main model code?  I'll think on this a bit and circle back.

**Comment by jrising** [comment]
@jkikstra @pwaidelich I am finally ready to merge this. I'm getting ready to start a project to make PAGE country-level, so I want to finalize it.

I've reduced a lot of code duplication, but kept the full range of options needed for our paper. My plan is to merge this into `master`, and then "archive `annualisedpage`, `growtheffectsscc`, `growtheffects_final`, and `regionspecificdamages_clean` branches by tagging them and then deleting them.

My unit test for these changes is extremely weak. I check that I can run each of the `runmodel...` scripts, and that they produce the right number of output files. I would welcome it if one of you wanted to check that we actually produce the same results, but I do not have time.

If there are no objections, I will do the merging and archiving on Monday.

**Comment by jkikstra** [comment]
Hi James, thanks for updating us and flagging this. Unfortunately also don't have time by Monday (will be on a conference). So I guess no objections from me. 
Moving to country level sounds great.

**Pull request merged**
