### PR TITLE
Adaptation to persistence - jsk: fix dependencies and mcs of newer mimi

### PR DESCRIPTION
**Pull request by jkikstra**
Based on #80, this PR also tries to include already PR #77 and PR #74 to get it running on my pc (kept getting parameter errors without it on new installation)

### CODE REVIEW

**Comment by lrennels** [comment]
@jkikstra I'd just wait a minute and @jrising and I can get #74 and #77 merged so you don't have to redo work!

**Comment by jkikstra** [comment]
Hi @lrennels - I was just resetting my julia installation and environment and struggled finding a workable setting, so just merged this in early to be able to reproduce some error that @jrising was getting. 
Wanted to explore it before night time today (CET) so went ahead and grabbed the great work you had already been doing!

But no worries, I will not merge this in separately but agree that #74 and #77 should go first.

**Comment by lrennels** [comment]
@jkikstra great, don't hesitate to bug me on the Mimi forum if you run into any environment issues!

**Comment by jrising** [comment]
Merging this into `AdaptationToPersistence` for the big final merge.

**Pull request merged**
